package com.example.carrier;

import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Set;

/**
 * For carriers we hand parcels to without an API: the operator books on the carrier's
 * own portal (or at the counter) and types the tracking number in.
 *
 * When nobody supplies a number one is generated so the shipment can be tracked inside
 * MyIndianStore — and flagged as generated, because it will not resolve on the
 * carrier's site.
 */
@Component
public class ManualCarrierAdapter implements CarrierAdapter {

    @Override
    public String key() {
        return CarrierAdapterRegistry.MANUAL;
    }

    @Override
    public String label() {
        return "Manual (no carrier API)";
    }

    @Override
    public boolean isConfigured() {
        return true;
    }

    @Override
    public Set<CarrierCapability> capabilities() {
        return Set.of(CarrierCapability.BOOKING);
    }

    @Override
    public List<String> requiredEnvironment() {
        return List.of();
    }

    @Override
    public BookingResult book(BookingRequest request) {
        String supplied = request.trackingNumber();
        if (supplied != null && !supplied.isBlank()) {
            return new BookingResult(supplied.trim(), false, null, null,
                "Tracking number entered by the shipper.");
        }
        String code = request.partnerCode() == null ? "SHP" : request.partnerCode();
        String prefix = code.length() >= 3 ? code.substring(0, 3) : code;
        String millis = Long.toString(System.currentTimeMillis());
        String generated = prefix + millis.substring(millis.length() - 9);
        return new BookingResult(generated, true, null, null,
            "Tracking number generated by MyIndianStore; it will not resolve on the carrier's site.");
    }
}
